### ISSUE TITLE
US 0.7 Construct UML Diagram

### ISSUE THREAD

**Issue by jteengfo** [Peer2Pressure/Peer2Pressure#46]
Create a UML diagram for p2p social network.

**Tasks when opening an issue**
- [x] Assigned a type to the issue
- [x] Assigned a severity to the issue
- [x] Assigned a milestone to the issue

**Comment by nevilkandathil** [comment]
A general idea of all classes and functions that will be required. *Changes will be made

### Classes
- **Author:** represents an author who creates posts and manages their profile. 
Post: represents a post created by an author. 
- **Image:** represents an image associated with a post. 
- **Server Admin:** represents a server administrator who manages the server and its authors. 
- **Friend:** represents a relationship between two authors.

### Associations
- Author creates Post 
- Post has Image 
- Author befriends Friend 
- Server Admin manages Author 
- Author re-shares Friend Post

### States/Operations: 
**Author:** 
- makePublicPost()
- editPublicPost()
- linkToImage()
- makePrivatePost()
- sharePost()
- re-shareFriendPost() 
- useBrowser()
- commentOnPost() 
- likePost()
- befriendAuthor()
- unfriendAuthor()
- knowFriendRequests()
- browsePublicPosts()
- makeUnlistedPost()

**Post:** 
- hasPlainText()
- hasCommonMark() 
- deletePost()

**Image:**
- hostedOnServer() 

**Server Admin:** 
- hostMultipleAuthors()
- sharePublicImages()
- addAuthor()
- modifyAuthor() 
- removeAuthor()
- requireAuthorOK() 
- restfulInterface()
- addNode()
- removeNode() 
- limitNodeConnection()
- authenticateNode()
- disableNodeInterface()

**Comment by nevilkandathil** [comment]
https://app.diagrams.net/#G1JlY3v-DjXOKct7T7ng0EF4ALdqFfrJfk
